### ISSUE TITLE
monero-wallet-cli, monero-wallet-gui not linking with boost libraries.

### ISSUE THREAD

**Issue by ethark** [gentoo-monero/gentoo-monero#19]
when I try to run monero-wallet-cli or monero-wallet-gui I get:
`monero-wallet-cli: error while loading shared libraries: libboost_chrono.so.1.75.0: cannot open shared object file: No such file or directory`
or 
`monero-wallet-gui: error while loading shared libraries: libboost_system.so.1.75.0: cannot open shared object file: No such file or directory` respectively.

I just installed the monero package, and I have =dev-libs/boost-1.76.0 installed. It looks like all the boost libraries are installed in /usr/lib64, so I don't know why it's not working.

**Comment by 00-matt** [comment]
Where did you get `monero-wallet-gui` from? We don't package that.

Please try rebuilding `net-p2p/monero`, although it is supposed to be rebuilt when you upgrade Boost, it seems to have linked to an older Boost version (1.75.0 vs. the 1.76.0 you have installed)

**Comment by ethark** [comment]
Sorry that was my bad, it was a leftover binary from when I tried to compile it myself a couple months ago
