### ISSUE TITLE
CMake configuration failure;  ZBAR seems to be involved

### ISSUE THREAD

**Issue by ArmouredHeart** [gentoo-monero/gentoo-monero#28]
emerge net-misc/feather fails at cmake configuration. I suspect ZBar is involved.

### Build Log
`# cat /var/tmp/portage/net-misc/feather-9999/temp/build.log
[32m * [39;49;00mPackage:    net-misc/feather-9999
[32m * [39;49;00mRepository: monero
[32m * [39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
[32m * [39;49;00mFEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 [32m*[0m Repository id: feather_feather.git
 [32m*[0m To override fetched repository properties, use:
 [32m*[0m   EGIT_OVERRIDE_REPO_FEATHER_FEATHER
 [32m*[0m   EGIT_OVERRIDE_BRANCH_FEATHER_FEATHER
 [32m*[0m   EGIT_OVERRIDE_COMMIT_FEATHER_FEATHER
 [32m*[0m   EGIT_OVERRIDE_COMMIT_DATE_FEATHER_FEATHER
 [32m*[0m 
 [32m*[0m Fetching https://git.featherwallet.org/feather/feather.git ...
git fetch https://git.featherwallet.org/feather/feather.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/net-misc/feather/0/__main__ refs/git-r3/HEAD
 [32m*[0m Repository id: feather_monero.git
 [32m*[0m To override fetched repository properties, use:
 [32m*[0m   EGIT_OVERRIDE_REPO_FEATHER_MONERO
 [32m*[0m   EGIT_OVERRIDE_BRANCH_FEATHER_MONERO
 [32m*[0m   EGIT_OVERRIDE_COMMIT_FEATHER_MONERO
 [32m*[0m   EGIT_OVERRIDE_COMMIT_DATE_FEATHER_MONERO
 [32m*[0m 
 [32m*[0m Fetching https://git.featherwallet.org/feather/monero.git ...
git fetch https://git.featherwallet.org/feather/monero.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/net-misc/feather/0/monero/__main__ 6a2b96394d3c81a4ccf9be0daea02afe5f6f3683
 [32m*[0m Repository id: monero-project_unbound.git
 [32m*[0m To override fetched repository properties, use:
 [32m*[0m   EGIT_OVERRIDE_REPO_MONERO_PROJECT_UNBOUND
 [32m*[0m   EGIT_OVERRIDE_BRANCH_MONERO_PROJECT_UNBOUND
 [32m*[0m   EGIT_OVERRIDE_COMMIT_MONERO_PROJECT_UNBOUND
 [32m*[0m   EGIT_OVERRIDE_COMMIT_DATE_MONERO_PROJECT_UNBOUND
 [32m*[0m 
 [32m*[0m Fetching https://github.com/monero-project/unbound ...
git fetch https://github.com/monero-project/unbound --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/net-misc/feather/0/monero/external_unbound/__main__ 0f6c0579d66b65f86066e30e7876105ba2775ef4
 [32m*[0m Repository id: miniupnp_miniupnp.git
 [32m*[0m To override fetched repository properties, use:
 [32m*[0m   EGIT_OVERRIDE_REPO_MINIUPNP_MINIUPNP
 [32m*[0m   EGIT_OVERRIDE_BRANCH_MINIUPNP_MINIUPNP
 [32m*[0m   EGIT_OVERRIDE_COMMIT_MINIUPNP_MINIUPNP
 [32m*[0m   EGIT_OVERRIDE_COMMIT_DATE_MINIUPNP_MINIUPNP
 [32m*[0m 
 [32m*[0m Fetching https://github.com/miniupnp/miniupnp ...
git fetch https://github.com/miniupnp/miniupnp --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/net-misc/feather/0/monero/external_miniupnp/__main__ 544e6fcc73c5ad9af48a8985c94f0f1d742ef2e0
 [32m*[0m Repository id: Tencent_rapidjson.git
 [32m*[0m To override fetched repository properties, use:
 [32m*[0m   EGIT_OVERRIDE_REPO_TENCENT_RAPIDJSON
 [32m*[0m   EGIT_OVERRIDE_BRANCH_TENCENT_RAPIDJSON
 [32m*[0m   EGIT_OVERRIDE_COMMIT_TENCENT_RAPIDJSON
 [32m*[0m   EGIT_OVERRIDE_COMMIT_DATE_TENCENT_RAPIDJSON
 [32m*[0m 
 [32m*[0m Fetching https://github.com/Tencent/rapidjson ...
git fetch https://github.com/Tencent/rapidjson --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/net-misc/feather/0/monero/external_rapidjson/__main__ 129d19ba7f496df5e33658527a7158c79b99c21c
 [32m*[0m Repository id: google_googletest.git
 [32m*[0m To override fetched repository properties, use:
 [32m*[0m   EGIT_OVERRIDE_REPO_GOOGLE_GOOGLETEST
 [32m*[0m   EGIT_OVERRIDE_BRANCH_GOOGLE_GOOGLETEST
 [32m*[0m   EGIT_OVERRIDE_COMMIT_GOOGLE_GOOGLETEST
 [32m*[0m   EGIT_OVERRIDE_COMMIT_DATE_GOOGLE_GOOGLETEST
 [32m*[0m 
 [32m*[0m Fetching https://github.com/google/googletest.git ...
git fetch https://github.com/google/googletest.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/net-misc/feather/0/monero/external_rapidjson/thirdparty_gtest/__main__ 0a439623f75c029912728d80cb7f1b8b48739ca4
 [32m*[0m Repository id: trezor_trezor-common.git
 [32m*[0m To override fetched repository properties, use:
 [32m*[0m   EGIT_OVERRIDE_REPO_TREZOR_TREZOR_COMMON
 [32m*[0m   EGIT_OVERRIDE_BRANCH_TREZOR_TREZOR_COMMON
 [32m*[0m   EGIT_OVERRIDE_COMMIT_TREZOR_TREZOR_COMMON
 [32m*[0m   EGIT_OVERRIDE_COMMIT_DATE_TREZOR_TREZOR_COMMON
 [32m*[0m 
 [32m*[0m Fetching https://github.com/trezor/trezor-common.git ...
git fetch https://github.com/trezor/trezor-common.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/net-misc/feather/0/monero/external_trezor-common/__main__ bff7fdfe436c727982cc553bdfb29a9021b423b0
 [32m*[0m Repository id: ethereum-lists_tokens.git
 [32m*[0m To override fetched repository properties, use:
 [32m*[0m   EGIT_OVERRIDE_REPO_ETHEREUM_LISTS_TOKENS
 [32m*[0m   EGIT_OVERRIDE_BRANCH_ETHEREUM_LISTS_TOKENS
 [32m*[0m   EGIT_OVERRIDE_COMMIT_ETHEREUM_LISTS_TOKENS
 [32m*[0m   EGIT_OVERRIDE_COMMIT_DATE_ETHEREUM_LISTS_TOKENS
 [32m*[0m 
 [32m*[0m Fetching https://github.com/ethereum-lists/tokens.git ...
git fetch https://github.com/ethereum-lists/tokens.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/net-misc/feather/0/monero/external_trezor-common/defs_ethereum_tokens/__main__ 88414ef852e21279f217d2f3f8fd439cd7c5fd9f
 [32m*[0m Repository id: tevador_RandomX.git
 [32m*[0m To override fetched repository properties, use:
 [32m*[0m   EGIT_OVERRIDE_REPO_TEVADOR_RANDOMX
 [32m*[0m   EGIT_OVERRIDE_BRANCH_TEVADOR_RANDOMX
 [32m*[0m   EGIT_OVERRIDE_COMMIT_TEVADOR_RANDOMX
 [32m*[0m   EGIT_OVERRIDE_COMMIT_DATE_TEVADOR_RANDOMX
 [32m*[0m 
 [32m*[0m Fetching https://github.com/tevador/RandomX ...
git fetch https://github.com/tevador/RandomX --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/net-misc/feather/0/monero/external_randomx/__main__ fe4324e8c0c035fec3affd6e4c49241c2e5b9955
 [32m*[0m Repository id: monero-project_supercop.git
 [32m*[0m To override fetched repository properties, use:
 [32m*[0m   EGIT_OVERRIDE_REPO_MONERO_PROJECT_SUPERCOP
 [32m*[0m   EGIT_OVERRIDE_BRANCH_MONERO_PROJECT_SUPERCOP
 [32m*[0m   EGIT_OVERRIDE_COMMIT_MONERO_PROJECT_SUPERCOP
 [32m*[0m   EGIT_OVERRIDE_COMMIT_DATE_MONERO_PROJECT_SUPERCOP
 [32m*[0m 
 [32m*[0m Fetching https://github.com/monero-project/supercop ...
git fetch https://github.com/monero-project/supercop --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/net-misc/feather/0/monero/external_supercop/__main__ 633500ad8c8759995049ccd022107d1fa8a1bbc9
 [32m*[0m Repository id: tor.git
 [32m*[0m To override fetched repository properties, use:
 [32m*[0m   EGIT_OVERRIDE_REPO_TOR
 [32m*[0m   EGIT_OVERRIDE_BRANCH_TOR
 [32m*[0m   EGIT_OVERRIDE_COMMIT_TOR
 [32m*[0m   EGIT_OVERRIDE_COMMIT_DATE_TOR
 [32m*[0m 
 [32m*[0m Fetching https://git.torproject.org/tor.git ...
git fetch https://git.torproject.org/tor.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/net-misc/feather/0/contrib_tor/__main__ e68770719ef4d3d3b83398715b1e10391ab6a1b4
 [32m*[0m Repository id: tor-rust-dependencies.git
 [32m*[0m To override fetched repository properties, use:
 [32m*[0m   EGIT_OVERRIDE_REPO_TOR_RUST_DEPENDENCIES
 [32m*[0m   EGIT_OVERRIDE_BRANCH_TOR_RUST_DEPENDENCIES
 [32m*[0m   EGIT_OVERRIDE_COMMIT_TOR_RUST_DEPENDENCIES
 [32m*[0m   EGIT_OVERRIDE_COMMIT_DATE_TOR_RUST_DEPENDENCIES
 [32m*[0m 
 [32m*[0m Fetching https://git.torproject.org/tor-rust-dependencies ...
git fetch https://git.torproject.org/tor-rust-dependencies --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/net-misc/feather/0/contrib_tor/src_ext_rust/__main__ aa37fb84fb829902e83ca11a7244bbc6b86b809b
 [32m*[0m Checking out https://git.featherwallet.org/feather/feather.git to /var/tmp/portage/net-misc/feather-9999/work/feather-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://git.featherwallet.org/feather/feather.git
   at the commit:            ffbaefd241435e314a86996cc52ff66a81b45c73
 [32m*[0m Checking out https://git.featherwallet.org/feather/monero.git to /var/tmp/portage/net-misc/feather-9999/work/feather-9999/monero ...
git checkout --quiet 6a2b96394d3c81a4ccf9be0daea02afe5f6f3683
GIT update -->
   repository:               https://git.featherwallet.org/feather/monero.git
   at the commit:            6a2b96394d3c81a4ccf9be0daea02afe5f6f3683
 [32m*[0m Checking out https://github.com/monero-project/unbound to /var/tmp/portage/net-misc/feather-9999/work/feather-9999/monero/external/unbound ...
git checkout --quiet 0f6c0579d66b65f86066e30e7876105ba2775ef4
GIT update -->
   repository:               https://github.com/monero-project/unbound
   at the commit:            0f6c0579d66b65f86066e30e7876105ba2775ef4
 [32m*[0m Checking out https://github.com/miniupnp/miniupnp to /var/tmp/portage/net-misc/feather-9999/work/feather-9999/monero/external/miniupnp ...
git checkout --quiet 544e6fcc73c5ad9af48a8985c94f0f1d742ef2e0
GIT update -->
   repository:               https://github.com/miniupnp/miniupnp
   at the commit:            544e6fcc73c5ad9af48a8985c94f0f1d742ef2e0
 [32m*[0m Checking out https://github.com/Tencent/rapidjson to /var/tmp/portage/net-misc/feather-9999/work/feather-9999/monero/external/rapidjson ...
git checkout --quiet 129d19ba7f496df5e33658527a7158c79b99c21c
GIT update -->
   repository:               https://github.com/Tencent/rapidjson
   at the commit:            129d19ba7f496df5e33658527a7158c79b99c21c
 [32m*[0m Checking out https://github.com/google/googletest.git to /var/tmp/portage/net-misc/feather-9999/work/feather-9999/monero/external/rapidjson/thirdparty/gtest ...
git checkout --quiet 0a439623f75c029912728d80cb7f1b8b48739ca4
GIT update -->
   repository:               https://github.com/google/googletest.git
   at the commit:            0a439623f75c029912728d80cb7f1b8b48739ca4
 [32m*[0m Checking out https://github.com/trezor/trezor-common.git to /var/tmp/portage/net-misc/feather-9999/work/feather-9999/monero/external/trezor-common ...
git checkout --quiet bff7fdfe436c727982cc553bdfb29a9021b423b0
GIT update -->
   repository:               https://github.com/trezor/trezor-common.git
   at the commit:            bff7fdfe436c727982cc553bdfb29a9021b423b0
 [32m*[0m Checking out https://github.com/ethereum-lists/tokens.git to /var/tmp/portage/net-misc/feather-9999/work/feather-9999/monero/external/trezor-common/defs/ethereum/tokens ...
git checkout --quiet 88414ef852e21279f217d2f3f8fd439cd7c5fd9f
GIT update -->
   repository:               https://github.com/ethereum-lists/tokens.git
   at the commit:            88414ef852e21279f217d2f3f8fd439cd7c5fd9f
 [32m*[0m Checking out https://github.com/tevador/RandomX to /var/tmp/portage/net-misc/feather-9999/work/feather-9999/monero/external/randomx ...
git checkout --quiet fe4324e8c0c035fec3affd6e4c49241c2e5b9955
GIT update -->
   repository:               https://github.com/tevador/RandomX
   at the commit:            fe4324e8c0c035fec3affd6e4c49241c2e5b9955
 [32m*[0m Checking out https://github.com/monero-project/supercop to /var/tmp/portage/net-misc/feather-9999/work/feather-9999/monero/external/supercop ...
git checkout --quiet 633500ad8c8759995049ccd022107d1fa8a1bbc9
GIT update -->
   repository:               https://github.com/monero-project/supercop
   at the commit:            633500ad8c8759995049ccd022107d1fa8a1bbc9
 [32m*[0m Checking out https://git.torproject.org/tor.git to /var/tmp/portage/net-misc/feather-9999/work/feather-9999/contrib/tor ...
git checkout --quiet e68770719ef4d3d3b83398715b1e10391ab6a1b4
GIT update -->
   repository:               https://git.torproject.org/tor.git
   at the commit:            e68770719ef4d3d3b83398715b1e10391ab6a1b4
 [32m*[0m Checking out https://git.torproject.org/tor-rust-dependencies to /var/tmp/portage/net-misc/feather-9999/work/feather-9999/contrib/tor/src/ext/rust ...
git checkout --quiet aa37fb84fb829902e83ca11a7244bbc6b86b809b
GIT update -->
   repository:               https://git.torproject.org/tor-rust-dependencies
   at the commit:            aa37fb84fb829902e83ca11a7244bbc6b86b809b
>>> Source unpacked in /var/tmp/portage/net-misc/feather-9999/work
>>> Preparing source in /var/tmp/portage/net-misc/feather-9999/work/feather-9999 ...
 [32m*[0m Source directory (CMAKE_USE_DIR): "/var/tmp/portage/net-misc/feather-9999/work/feather-9999"
 [32m*[0m Build directory  (BUILD_DIR):     "/var/tmp/portage/net-misc/feather-9999/work/feather-9999_build"
 [32m*[0m Hardcoded definition(s) removed in monero/CMakeLists.txt:
 [32m*[0m    set(CMAKE_BUILD_TYPE Release CACHE STRING "Build type" FORCE)
 [32m*[0m Hardcoded definition(s) removed in monero/external/randomx/CMakeLists.txt:
 [32m*[0m    set(CMAKE_BUILD_TYPE Release)
 [32m*[0m Hardcoded definition(s) removed in monero/external/rapidjson/CMakeLists.txt:
 [32m*[0m      set(CMAKE_BUILD_TYPE "RelWithDebInfo" CACHE STRING "Choose the type of bu
 [32m*[0m Hardcoded definition(s) removed in CMakeLists.txt:
 [32m*[0m      set(CMAKE_VERBOSE_MAKEFILE ON)
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/net-misc/feather-9999/work/feather-9999 ...
 [32m*[0m Source directory (CMAKE_USE_DIR): "/var/tmp/portage/net-misc/feather-9999/work/feather-9999"
 [32m*[0m Build directory  (BUILD_DIR):     "/var/tmp/portage/net-misc/feather-9999/work/feather-9999_build"
cmake -C /var/tmp/portage/net-misc/feather-9999/work/feather-9999_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DARCH=x86-64 -DBUILD_64=ON -DBUILD_SHARED_LIBS=Off -DBUILD_TAG=linux-x64 -DBUILD_TESTS=OFF -DDONATE_BEG=OFF -DINSTALL_VENDORED_LIBUNBOUND=OFF -DMANUAL_SUBMODULES=1 -DSTATIC=OFF -DUSE_DEVICE_TREZOR=OFF -DXMRIG=no -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/net-misc/feather-9999/work/feather-9999_build/gentoo_toolchain.cmake  /var/tmp/portage/net-misc/feather-9999/work/feather-9999
loading initial cache file /var/tmp/portage/net-misc/feather-9999/work/feather-9999_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Initiating compile using CMake 3.21.4
[0mccache NOT found![0m
-- Looking for sys/prctl.h
-- Looking for sys/prctl.h - found
-- Looking for prctl
-- Looking for prctl - found
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- [submodule] Monero HEAD @ 6a2b96394d3c81a4ccf9be0daea02afe5f6f3683
-- Found PythonInterp: /usr/bin/python (found version "3.9.9") 
[0mCMake Deprecation Warning at monero/CMakeLists.txt:46 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

[0m
-- CMake version 3.21.4
-- ccache NOT found! Please install it for faster rebuilds.
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Looking for -Wl,--no-undefined linker flag
-- Looking for -Wl,--no-undefined linker flag - found
-- Looking for -Wl,-undefined,error linker flag
-- Looking for -Wl,-undefined,error linker flag - found
-- Building build tag linux-x64
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
[33mCMake Warning (dev) at monero/CMakeLists.txt:344 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_64'.
This warning is for project developers.  Use -Wno-dev to suppress it.
[0m
-- Building for a 64-bit system
-- Building internal libraries as static
-- Using LMDB as default DB type
-- Stack trace on exception enabled (using easylogging++)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test _Werror__pthread_c
-- Performing Test _Werror__pthread_c - Success
-- Performing Test _Werror__pthread_cxx
-- Performing Test _Werror__pthread_cxx - Success
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1l")  
-- Using OpenSSL include dir at /usr/include
-- Could NOT find HIDAPI (missing: HIDAPI_LIBRARY HIDAPI_INCLUDE_DIR) 
-- Looking for memset_s in c
-- Looking for memset_s in c - not found
-- Looking for explicit_bzero in c
-- Looking for explicit_bzero in c - found
-- Looking for strptime
-- Looking for strptime - found
-- Looking for libunbound
-- Found libunbound include (unbound.h) in /usr/include
-- Found libunbound shared library
-- Using 64-bit LMDB from source tree
[0mCMake Deprecation Warning at monero/external/easylogging++/CMakeLists.txt:29 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

[0m
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Backtrace_LIBRARY: 
-- Found Backtrace: /usr/include  
[0mCMake Deprecation Warning at monero/external/randomx/CMakeLists.txt:29 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

[0m
-- Performing Test _maes_cxx
-- Performing Test _maes_cxx - Success
-- Setting CXX flag -maes
-- Performing Test _maes_c
-- Performing Test _maes_c - Success
-- Setting C flag -maes
-- Performing Test HAVE_SSSE3
-- Performing Test HAVE_SSSE3 - Success
-- Performing Test HAVE_AVX2
-- Performing Test HAVE_AVX2 - Success
-- Performing Test HAVE_CXX_ATOMICS
-- Performing Test HAVE_CXX_ATOMICS - Success
-- Could not find HIDAPI
-- Trezor support disabled by USE_DEVICE_TREZOR
-- Building on x86_64 for x86-64
-- AES support enabled
-- Performing Test _Werror__Wformat_c
-- Performing Test _Werror__Wformat_c - Success
-- Performing Test _Werror__Wformat_cxx
-- Performing Test _Werror__Wformat_cxx - Success
-- Performing Test _Werror__Wformat_security_c
-- Performing Test _Werror__Wformat_security_c - Success
-- Performing Test _Werror__Wformat_security_cxx
-- Performing Test _Werror__Wformat_security_cxx - Success
-- Performing Test _Werror__fstack_protector_c
-- Performing Test _Werror__fstack_protector_c - Success
-- Performing Test _Werror__fstack_protector_cxx
-- Performing Test _Werror__fstack_protector_cxx - Success
-- Performing Test _Werror__fstack_protector_strong_c
-- Performing Test _Werror__fstack_protector_strong_c - Success
-- Performing Test _Werror__fstack_protector_strong_cxx
-- Performing Test _Werror__fstack_protector_strong_cxx - Success
-- Performing Test _Werror__fcf_protection=full_c
-- Performing Test _Werror__fcf_protection=full_c - Success
-- Performing Test _Werror__fcf_protection=full_cxx
-- Performing Test _Werror__fcf_protection=full_cxx - Success
-- Performing Test _Werror__fstack_clash_protection_c
-- Performing Test _Werror__fstack_clash_protection_c - Success
-- Performing Test _Werror__fstack_clash_protection_cxx
-- Performing Test _Werror__fstack_clash_protection_cxx - Success
-- Looking for -pie linker flag
-- Looking for -pie linker flag - found
-- Looking for -Wl,-z,relro linker flag
-- Looking for -Wl,-z,relro linker flag - found
-- Looking for -Wl,-z,now linker flag
-- Looking for -Wl,-z,now linker flag - found
-- Looking for -Wl,-z,noexecstack linker flag
-- Looking for -Wl,-z,noexecstack linker flag - found
-- Looking for -Wl,-z,noexecheap linker flag
-- Looking for -Wl,-z,noexecheap linker flag - not found
-- Using C security hardening flags:  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fcf-protection=full -fstack-clash-protection
-- Using C++ security hardening flags:  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -fcf-protection=full -fstack-clash-protection
-- Using linker security hardening flags:  -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
-- Found Boost Version: 107700
-- Looking for rl_copy_text
-- Looking for rl_copy_text - found
-- Looking for rl_filename_completion_function
-- Looking for rl_filename_completion_function - found
-- Found readline library at: /usr
[0mWallet crypto is using amd64-64-24k backend[0m
-- Trezor support disabled
-- Not building tests
-- Not building debug utilities
[0mDoxygen: graphviz not found - graphs disabled[0m
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
[33mCMake Warning (dev) at monero/CMakeLists.txt:1118 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_GUI_DEPS'.
This warning is for project developers.  Use -Wno-dev to suppress it.
[0m
-- Performing Test HAVE_C11
-- Performing Test HAVE_C11 - Success
-- You are currently on commit 6a2b96394
-- Cannot determine most recent tag. Make sure that you are building either from a Git working tree or from a source archive.
fatal: not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[33mCMake Warning at cmake/VersionFeather.cmake:12 (message):
  Cannot determine current commit.  Make sure that you are building either
  from a Git working tree or from a source archive.
Call Stack (most recent call first):
  CMakeLists.txt:79 (include)

[0m
-- OpenSSL: Version 1.1.1l
-- OpenSSL: include dir at /usr/include
-- OpenSSL: libraries at /usr/lib64/libssl.so;/usr/lib64/libcrypto.so /usr/lib64/libssl.so
-- libsodium: libraries at /usr/lib64/libsodium.so
-- QRENCODE PATH /usr/include
-- QRENCODE LIBARY /usr/lib64/libqrencode.so
-- Found QREncode: /usr/lib64/libqrencode.so  
-- Found PkgConfig: x86_64-pc-linux-gnu-pkg-config (found version "1.8.0") 
[31mCMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZBAR (missing: ZBAR_LIBRARIES ZBAR_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindZBAR.cmake:28 (find_package_handle_standard_args)
  CMakeLists.txt:104 (find_package)

[0m
-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/net-misc/feather-9999/work/feather-9999_build/CMakeFiles/CMakeOutput.log".
See also "/var/tmp/portage/net-misc/feather-9999/work/feather-9999_build/CMakeFiles/CMakeError.log".
 [31;01m*[0m ERROR: net-misc/feather-9999::monero failed (configure phase):
 [31;01m*[0m   cmake failed
 [31;01m*[0m 
 [31;01m*[0m Call stack:
 [31;01m*[0m     ebuild.sh, line  127:  Called src_configure
 [31;01m*[0m   environment, line 2652:  Called cmake_src_configure
 [31;01m*[0m   environment, line 1136:  Called die
 [31;01m*[0m The specific snippet of code:
 [31;01m*[0m       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 [31;01m*[0m 
 [31;01m*[0m If you need support, post the output of `emerge --info '=net-misc/feather-9999::monero'`,
 [31;01m*[0m the complete build log and the output of `emerge -pqv '=net-misc/feather-9999::monero'`.
 [31;01m*[0m The complete build log is located at '/var/tmp/portage/net-misc/feather-9999/temp/build.log'.
 [31;01m*[0m The ebuild environment file is located at '/var/tmp/portage/net-misc/feather-9999/temp/environment'.
 [31;01m*[0m Working directory: '/var/tmp/portage/net-misc/feather-9999/work/feather-9999_build'
 [31;01m*[0m S: '/var/tmp/portage/net-misc/feather-9999/work/feather-9999'`

**Comment by 00-matt** [comment]
Thank you for the report. It looks like c2fbdbccfd8b24fe7b40ea11e1f8577107509777 which added the qrcode use flag didn't add the `-DWITH_SCANNER`.
