### ISSUE TITLE
Add USE flags for the net-p2p/monero binaries

### ISSUE THREAD

**Issue by 00-matt** [gentoo-monero/gentoo-monero#4]
It would be nice if there were USE flags so that users can choose which pieces of the Monero software to install, e.g. just `monerod` or just `monero-wallet-cli`.

**Comment by ernsteiswuerfel** [comment]
IMHO I doubt this is worth the effort.

Most stuff simply won't make sense without `monerod`. And if you build monerod you probably want `monero-wallet-cli` (and perhaps other stuff) as well. Perhaps it's good enough to add some more USE flags for the more relevant USE cases.

**Comment by 00-matt** [comment]
I was thinking that it could be useful for software that needs to link with Monero's libraries, like pools or third-party wallets. But thank you for the suggestion, I think you're right that USE flags are the way to go here.

**Comment by 00-matt** [comment]
Done in https://github.com/gentoo-monero/gentoo-monero/commit/f099f68030e92cc8e3a529e33e3dabfdd2462e71. Will leave it in another branch until the next release to prevent unnecessary rebuilds.
