### ISSUE TITLE
net-p2p/monero: please add libressl support

### ISSUE THREAD

**Issue by ernsteiswuerfel** [gentoo-monero/gentoo-monero#6]
Would be nice if there was libressl support in the monero ebuilds. I patched your monero-0.17.0.0 to add that, which worked well.

[libressl.patch.txt](https://github.com/gentoo-monero/gentoo-monero/files/5292477/libressl.patch.txt)

**Comment by 00-matt** [comment]
Thank you for the patch.

I noticed that you disallowed the OpenSSL bindist USE flag, is there a
reason for this? It seems like Monero uses OpenSSL (or LibreSSL :)) for
some hashing and for TLS between daemon and wallet, which should still
work with +bindist.

**Comment by ernsteiswuerfel** [comment]
No special reason. You are right, +bindist probably will be no problem. I just copied over this part from another custom ebuild where I 'added' libressl support. I just don't build with bindist USE flag.

**Comment by ernsteiswuerfel** [comment]
Thanks!

**Comment by ernsteiswuerfel** [comment]
Small bug: you forgot to remove the
`dev-libs/openssl:=`
line. It's still pulling in openssl, despite +libressl is set.

**Comment by 00-matt** [comment]
Sorry, not sure how I managed to mess that up :x - updated.
